/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by multi_energy_agent/api/generate_ts_models.py
 */

export type ScenarioStatus = 'pending' | 'running' | 'completed' | 'failed';

export interface ScenarioRequest {
  selection?: Record<string, any>;
  scenario?: Record<string, any>;
  inputs?: Record<string, any>;
  output_root?: string;
}

export interface ScenarioEvent {
  event_id: string;
  run_id: string;
  event: string;
  created_at: string;
  stage?: string | null;
  message?: string | null;
  payload?: Record<string, any>;
}

export interface ScenarioCreateResponse {
  run_id: string;
  scenario_id: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  created_at: string;
}

export interface ScenarioSummary {
  run_id: string;
  scenario_id: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  created_at: string;
  updated_at: string;
}

export interface ScenarioDetailResponse {
  run_id: string;
  scenario_id: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  created_at: string;
  updated_at: string;
  selection: Record<string, any>;
  scenario: Record<string, any>;
  inputs: Record<string, any>;
  events: ScenarioEvent[];
  result?: Record<string, any> | null;
  error?: string | null;
}
