"""Generate TypeScript models from backend Pydantic models.

Project requirement:
- 后端以 Pydantic 定义
- 前端以 TS 生成/同步

This script generates `multi_energy_agent/api/ts/models.ts`.

It is intentionally lightweight (no external generators), covering the models
exposed by the FastAPI backend.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Type, Union, get_args, get_origin

from pydantic import BaseModel

# Allow running as both module and script.
import importlib
import sys

if __package__ is None or __package__ == "":
    # repo root (energy_llm/) should be on sys.path
    sys.path.append(str(Path(__file__).resolve().parents[2]))

api_models = importlib.import_module("multi_energy_agent.api.models")


@dataclass
class TsDecl:
    name: str
    body: str


def _ts_type(anno: Any) -> str:
    # Handle Optional/Union
    origin = get_origin(anno)
    args = get_args(anno)
    if origin is Union:
        non_none = [a for a in args if a is not type(None)]  # noqa: E721
        has_none = len(non_none) != len(args)
        if len(non_none) == 1:
            t = _ts_type(non_none[0])
            return f"{t} | null" if has_none else t
        # fallback union
        parts = [_ts_type(a) for a in non_none]
        if has_none:
            parts.append("null")
        return " | ".join(sorted(set(parts)))

    # Containers
    if origin in (list, List):
        inner = _ts_type(args[0]) if args else "any"
        return f"{inner}[]"
    if origin in (dict, Dict):
        k = _ts_type(args[0]) if args else "string"
        v = _ts_type(args[1]) if len(args) > 1 else "any"
        if k == "string":
            return f"Record<string, {v}>"
        return f"Record<{k}, {v}>"

    # Primitives
    if anno in (str,):
        return "string"
    if anno in (int, float):
        return "number"
    if anno is bool:
        return "boolean"
    if anno is Any:
        return "any"
    if anno is datetime:
        return "string"  # ISO datetime

    # Enum
    if isinstance(anno, type) and issubclass(anno, Enum):
        vals = []
        for m in anno:
            if isinstance(m.value, str):
                vals.append(repr(m.value))
            else:
                vals.append(str(m.value))
        return " | ".join(vals) if vals else "string"

    # Pydantic model
    if isinstance(anno, type) and issubclass(anno, BaseModel):
        return anno.__name__

    # fallback
    return "any"


def _render_interface(model: Type[BaseModel]) -> TsDecl:
    lines: List[str] = []
    for fname, finfo in model.model_fields.items():
        anno = finfo.annotation
        t = _ts_type(anno)
        optional = not finfo.is_required()
        # keep property names identical to backend
        prop = f"{fname}{'?' if optional else ''}: {t};"
        lines.append(prop)
    body = "\n".join(lines)
    return TsDecl(name=model.__name__, body=body)


def generate(output_path: Path) -> str:
    decls: List[TsDecl] = []

    # Enums
    decls.append(TsDecl(name="ScenarioStatus", body=f"export type ScenarioStatus = {_ts_type(api_models.ScenarioStatus)};"))

    # Models
    for m in [
        api_models.ScenarioRequest,
        api_models.ScenarioEvent,
        api_models.ScenarioCreateResponse,
        api_models.ScenarioSummary,
        api_models.ScenarioDetailResponse,
    ]:
        d = _render_interface(m)
        decls.append(TsDecl(name=d.name, body=f"export interface {d.name} {{\n{_indent(d.body)}\n}}"))

    header = (
        "/* AUTO-GENERATED FILE. DO NOT EDIT.\n"
        " * Generated by multi_energy_agent/api/generate_ts_models.py\n"
        " */\n\n"
    )

    content = header + "\n\n".join(d.body for d in decls) + "\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return content


def _indent(s: str, n: int = 2) -> str:
    pad = " " * n
    return "\n".join(pad + line if line.strip() else line for line in s.splitlines())


if __name__ == "__main__":
    out = Path(__file__).parent / "ts" / "models.ts"
    generate(out)
    print(f"generated: {out}")
